using Discord;
using System;

namespace SIlverCraftBot
{
    internal static class Splashes
    {
        public static Tuple<string, ActivityType>[] Get { get; } = {
new Tuple<string, ActivityType>("D̶U̶K̶T̶  Silver Hosting", ActivityType.Watching),
new Tuple<string, ActivityType>("As seen on TV!", ActivityType.Playing),
new Tuple<string, ActivityType>("100% pure!", ActivityType.Playing),
new Tuple<string, ActivityType>("20 GOTO 10!", ActivityType.Playing),
new Tuple<string, ActivityType>("Déjà vu!",ActivityType.Playing),
new Tuple<string, ActivityType>("Déjà vu!",ActivityType.Playing),
new Tuple<string, ActivityType>("Does barrel rolls!",ActivityType.Playing),
new Tuple<string, ActivityType>("Follow the train, CJ!",ActivityType.Playing),
new Tuple<string, ActivityType>("NOT Google anlyticsed!",ActivityType.Playing),
new Tuple<string, ActivityType>("Beta!",ActivityType.Playing),
new Tuple<string, ActivityType>("Internet enabled!",ActivityType.Playing),
new Tuple<string, ActivityType>("David please look at your table",ActivityType.Playing),
new Tuple<string, ActivityType>("Its a bot!",ActivityType.Playing),
new Tuple<string, ActivityType>("Made in Macedonia",ActivityType.Playing),
new Tuple<string, ActivityType>("Now supports emoji :wink:",ActivityType.Playing),
new Tuple<string, ActivityType>("Creeper aw man.",ActivityType.Playing),
new Tuple<string, ActivityType>("if not ok then return end",ActivityType.Playing),
new Tuple<string, ActivityType>("Now on [insert platform here].",ActivityType.Playing),
new Tuple<string, ActivityType>("String[] splashes",ActivityType.Playing),
new Tuple<string, ActivityType>("Limited edition!",ActivityType.Playing),
new Tuple<string, ActivityType>("Should not be texted while driving",ActivityType.Playing),
new Tuple<string, ActivityType>("Try it!",ActivityType.Playing),
new Tuple<string, ActivityType>("Have you finished your homework?",ActivityType.Playing),
new Tuple<string, ActivityType>("UwU whats dis",ActivityType.Playing),
new Tuple<string, ActivityType>("Digital Dancing!",ActivityType.Playing),
new Tuple<string, ActivityType>("5 is best number!",ActivityType.Playing),
new Tuple<string, ActivityType>("MCROC++!",ActivityType.Playing),
new Tuple<string, ActivityType>("Plastic Guns!",ActivityType.Playing),
new Tuple<string, ActivityType>("Lines from 2004!",ActivityType.Playing),
new Tuple<string, ActivityType>("Absolutely no sarcasm!",ActivityType.Playing),
new Tuple<string, ActivityType>("Thinking involved!",ActivityType.Playing),
new Tuple<string, ActivityType>("huehuehue",ActivityType.Playing),
new Tuple<string, ActivityType>("!gnilleps sdrawkcab",ActivityType.Playing),
new Tuple<string, ActivityType>("xXPr0$n1p3$Xx",ActivityType.Playing),
new Tuple<string, ActivityType>("Sharpshooter!",ActivityType.Playing),
new Tuple<string, ActivityType>("Tsar Bomba!",ActivityType.Playing),
new Tuple<string, ActivityType>("Vive l'atome!",ActivityType.Playing),
new Tuple<string, ActivityType>("10% Milk!",ActivityType.Playing),
new Tuple<string, ActivityType>("Available in stores!",ActivityType.Playing),
new Tuple<string, ActivityType>("Gluten Free!",ActivityType.Playing),
new Tuple<string, ActivityType>("But wait there's more!",ActivityType.Playing),
new Tuple<string, ActivityType>("How much do you think SilverBot is worth. Think one minute before you anwser.",ActivityType.Playing),
new Tuple<string, ActivityType>("RREEEEE",ActivityType.Playing),
new Tuple<string, ActivityType>("except in nebraska",ActivityType.Playing),
new Tuple<string, ActivityType>("Above Average Man!",ActivityType.Playing),
new Tuple<string, ActivityType>("ThinThick is better than Swag",ActivityType.Playing),
new Tuple<string, ActivityType>("Glorified Drift Wood!",ActivityType.Playing),
new Tuple<string, ActivityType>("T0P K3K",ActivityType.Playing),
new Tuple<string, ActivityType>("Maximizing Profits!",ActivityType.Playing),
new Tuple<string, ActivityType>("Somewhat Persuasive!",ActivityType.Playing),
new Tuple<string, ActivityType>("am vary smert",ActivityType.Playing),
new Tuple<string, ActivityType>("Blue!",ActivityType.Playing),
new Tuple<string, ActivityType>("splashes.json",ActivityType.Playing),
new Tuple<string, ActivityType>("Green!",ActivityType.Playing),
new Tuple<string, ActivityType>("1nd Floor!",ActivityType.Playing),
new Tuple<string, ActivityType>("wait this isn't mee6",ActivityType.Playing),
new Tuple<string, ActivityType>("fReE cAkE>>",ActivityType.Playing),
new Tuple<string, ActivityType>("Exclamation Mark!",ActivityType.Playing),
new Tuple<string, ActivityType>("Strongly Dislikes Birch!",ActivityType.Playing),
new Tuple<string, ActivityType>("Bestest Grammar!",ActivityType.Playing),
new Tuple<string, ActivityType>("feedback plz",ActivityType.Playing),
new Tuple<string, ActivityType>("Relevant Text!",ActivityType.Playing),
new Tuple<string, ActivityType>("finally in beta",ActivityType.Playing),
new Tuple<string, ActivityType>("needs update",ActivityType.Playing),
new Tuple<string, ActivityType>("Woah!",ActivityType.Playing),
new Tuple<string, ActivityType>("fruit salad is best salad",ActivityType.Playing),
new Tuple<string, ActivityType>("75% less random!",ActivityType.Playing),
new Tuple<string, ActivityType>("Move now, think later!",ActivityType.Playing),
new Tuple<string, ActivityType>("*teleports behind you*",ActivityType.Playing),
new Tuple<string, ActivityType>("4 Letters!",ActivityType.Playing),
new Tuple<string, ActivityType>("Brandon yes",ActivityType.Playing),
new Tuple<string, ActivityType>("Show your face pixels!",ActivityType.Playing),
new Tuple<string, ActivityType>("Less than Minimum!",ActivityType.Playing),
new Tuple<string, ActivityType>("****need copy and link****",ActivityType.Playing),
new Tuple<string, ActivityType>("Flatter than Kansas!",ActivityType.Playing),
new Tuple<string, ActivityType>("Not a Fan of Fuzzies!",ActivityType.Playing),
new Tuple<string, ActivityType>("Consider Fullscreen!",ActivityType.Playing),
new Tuple<string, ActivityType>("The Exits are... Irrelevant!",ActivityType.Playing),
new Tuple<string, ActivityType>("The facts they dont want you to know",ActivityType.Playing),
new Tuple<string, ActivityType>("max should not be trusted",ActivityType.Playing),
new Tuple<string, ActivityType>("6.9' is noice",ActivityType.Playing),
new Tuple<string, ActivityType>("LE:L",ActivityType.Playing),
new Tuple<string, ActivityType>("requires additional pylons",ActivityType.Playing),
new Tuple<string, ActivityType>("THAT FACE DOWN",ActivityType.Playing),
new Tuple<string, ActivityType>("Heterogeneous Greens!",ActivityType.Playing),
new Tuple<string, ActivityType>("Old White French House!",ActivityType.Playing),
new Tuple<string, ActivityType>("Really Dark Purples!",ActivityType.Playing),
new Tuple<string, ActivityType>("Two Ups Thumb!",ActivityType.Playing),
new Tuple<string, ActivityType>("Gilden Ultra Cotton Pocket Tee!",ActivityType.Playing),
new Tuple<string, ActivityType>("Crazy Cool Coincidence!",ActivityType.Playing),
new Tuple<string, ActivityType>("Over the mountains, into Terrellia!",ActivityType.Playing),
new Tuple<string, ActivityType>("Your content is good!",ActivityType.Playing),
new Tuple<string, ActivityType>("striker disapproves",ActivityType.Playing),
new Tuple<string, ActivityType>("Fools' Gold!",ActivityType.Playing),
new Tuple<string, ActivityType>("Powered by Wind!",ActivityType.Playing),
new Tuple<string, ActivityType>("Globular Resources!",ActivityType.Playing),
new Tuple<string, ActivityType>("Falcon Heavy!",ActivityType.Playing),
new Tuple<string, ActivityType>("shoutout to me beta testers",ActivityType.Playing),
new Tuple<string, ActivityType>("Acid Trips!",ActivityType.Playing),
new Tuple<string, ActivityType>("lttstore.com",ActivityType.Playing),
new Tuple<string, ActivityType>("Wonder-filly-ful!",ActivityType.Playing),
new Tuple<string, ActivityType>("Nostalgic!",ActivityType.Playing),
new Tuple<string, ActivityType>("Giv quadratic formula or I kill",ActivityType.Playing),
new Tuple<string, ActivityType>("T-shape is cancer",ActivityType.Playing),
new Tuple<string, ActivityType>("som splashes for u ^_^",ActivityType.Playing),
new Tuple<string, ActivityType>("0% less memory!",ActivityType.Playing),
new Tuple<string, ActivityType>("ThePajamaSlime has invited you to play Minecraft",ActivityType.Playing),
new Tuple<string, ActivityType>("ThePajamaSlime! ThePajamaSlime! ThePajamaSlime!",ActivityType.Playing),
new Tuple<string, ActivityType>("Xbox 360 Edition",ActivityType.Playing),
new Tuple<string, ActivityType>("sign in with your microsoft account",ActivityType.Playing),
new Tuple<string, ActivityType>("Now with 69% more ThePajamaSlime!",ActivityType.Playing),
new Tuple<string, ActivityType>("Teach me the stats!",ActivityType.Playing),
new Tuple<string, ActivityType>("capped image of caps with captions in caps",ActivityType.Playing),
new Tuple<string, ActivityType>("buy shark tale on dvd",ActivityType.Playing),
new Tuple<string, ActivityType>("subscribe to idots",ActivityType.Playing),
new Tuple<string, ActivityType>("Cinnamon oat cereal!",ActivityType.Playing),
new Tuple<string, ActivityType>("Silver chest unlocked!",ActivityType.Playing),
new Tuple<string, ActivityType>("Flame-Headed Boy!",ActivityType.Playing),
new Tuple<string, ActivityType>("lamo",ActivityType.Playing),
new Tuple<string, ActivityType>("Non-Newtonian Fluids!",ActivityType.Playing),
new Tuple<string, ActivityType>("Intensive and Extensive!",ActivityType.Playing),
new Tuple<string, ActivityType>("Aquatic!",ActivityType.Playing),
new Tuple<string, ActivityType>("4TH DOWN AND 9!",ActivityType.Playing),
new Tuple<string, ActivityType>("pls r8 5",ActivityType.Playing),
new Tuple<string, ActivityType>("dabbing on them endermans",ActivityType.Playing),
new Tuple<string, ActivityType>("GIMP FTW",ActivityType.Playing),
new Tuple<string, ActivityType>("Bush hid the facts",ActivityType.Playing),
new Tuple<string, ActivityType>("ugh, finally, no more sugar",ActivityType.Playing),
new Tuple<string, ActivityType>("-1 splash per update?",ActivityType.Playing),
new Tuple<string, ActivityType>("uploading...41%",ActivityType.Playing),
new Tuple<string, ActivityType>("my stuff stuff",ActivityType.Playing),
new Tuple<string, ActivityType>("teleporting-porter-pearl",ActivityType.Playing),
new Tuple<string, ActivityType>("bot now has graphics, you're welcome",ActivityType.Playing),
new Tuple<string, ActivityType>("(it's a list, not a method)",ActivityType.Playing),
new Tuple<string, ActivityType>("superb bus service",ActivityType.Playing),
new Tuple<string, ActivityType>("SELCET? AWESMOE!",ActivityType.Playing),
new Tuple<string, ActivityType>("pretty pink spigots",ActivityType.Playing),
new Tuple<string, ActivityType>("you're uh winner",ActivityType.Playing),
new Tuple<string, ActivityType>("wifi killed the dinosaurs",ActivityType.Playing),
new Tuple<string, ActivityType>("60 layers of wax",ActivityType.Playing),
new Tuple<string, ActivityType>("12 years later",ActivityType.Playing),
new Tuple<string, ActivityType>("it came in teal!",ActivityType.Playing),
new Tuple<string, ActivityType>("pretend the sun is real",ActivityType.Playing),
new Tuple<string, ActivityType>("people hate people",ActivityType.Playing),
new Tuple<string, ActivityType>("north of what?",ActivityType.Playing),
new Tuple<string, ActivityType>("non-lethal stabbing",ActivityType.Playing),
new Tuple<string, ActivityType>("pertrify yourself!",ActivityType.Playing),
new Tuple<string, ActivityType>("pay the poor",ActivityType.Playing),
new Tuple<string, ActivityType>("check your spam!",ActivityType.Playing),
new Tuple<string, ActivityType>("say PLEASE next time!",ActivityType.Playing),
new Tuple<string, ActivityType>("see it with your ears!",ActivityType.Playing),
new Tuple<string, ActivityType>("hear it with your eyes!",ActivityType.Playing),
new Tuple<string, ActivityType>("it'll change, soon!",ActivityType.Playing),
new Tuple<string, ActivityType>("space is key!",ActivityType.Playing),
new Tuple<string, ActivityType>("for the love of god dont use dukt hosting",ActivityType.Playing),
new Tuple<string, ActivityType>("max is bad?",ActivityType.Playing),
new Tuple<string, ActivityType>("Smash Mouth - All Star",ActivityType.Playing),
new Tuple<string, ActivityType>("indentetion error",ActivityType.Watching),
new Tuple<string, ActivityType>("in 5,4,3,2,1 I know you see",ActivityType.Playing),
new Tuple<string, ActivityType>("the world will change for me",ActivityType.Playing),
new Tuple<string, ActivityType>("and be so wonderful",ActivityType.Playing),
new Tuple<string, ActivityType>("https://www.youtube.com/watch?v=HPM05dQgdig",ActivityType.Playing),
new Tuple<string, ActivityType>("RIP XBOX360",ActivityType.Playing),
new Tuple<string, ActivityType>("https://catjam.tk/",ActivityType.Playing),
new Tuple<string, ActivityType>("Leave it all to me",ActivityType.Listening),
new Tuple<string, ActivityType>("Thanks ThePajamaSlime!",ActivityType.Playing),
new Tuple<string, ActivityType>("10000000% c# by 1969",ActivityType.Playing),
new Tuple<string, ActivityType>("Prouldly europian",ActivityType.Playing),
new Tuple<string, ActivityType>("@everyone",ActivityType.Playing),
new Tuple<string, ActivityType>("2 meters apart",ActivityType.Playing),
new Tuple<string, ActivityType>("ERROR",ActivityType.Playing),
new Tuple<string, ActivityType>("THE CAKE IS A LIE",ActivityType.Playing),
new Tuple<string, ActivityType>("ThE CaKe Is A lIe",ActivityType.Playing),
        };
    }
}